[package]
name = "platform-config-derive"
version = "0.1.0"
authors = ["Marcin Sas-Szymanski <marcin.sas-szymanski@anixe.pl>"]

[dependencies]
syn = "0.12"
quote = "0.4"
proc-macro2 = "0.2"
structopt = "0.2.4"
structopt-derive = "0.2.4"

[lib]
proc-macro = true
